import { readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildViewModel } from './scripts/feed-model.mjs'

// Build-time templater for the project-intelligence body-of-work index (S1 overview + S2 index).
// Renders the feed-model view model into projects/index.html — a BUILD ARTIFACT (gitignored),
// regenerated by `npm run feed` in pre(dev|build). No client JS; the rules live in assets/jeffrey.css.
// Per docs/meta-inventory-website-contract.md, only feed-present fields are rendered — nothing is
// derived from outside the public feed. S3 (per-project panel) and the S1 methods line await feed v1.
// Spec: docs/project-intelligence-design-spec-2026-06-16.md.

const root = path.dirname(fileURLToPath(import.meta.url))
const OUT = 'projects/index.html'

const ESC = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }
const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ESC[c])

// First clause of a status line keeps the row to one line: "Alpha (working prototype)" -> "Alpha".
const trimStatus = (s) => (s ? s.split(/,| \(/)[0].trim() : '')
const hasYear = (s) => /\d{4}/.test(s ?? '')
const hostOf = (url) => url.replace(/^https?:\/\//, '').replace(/\/$/, '')

function leakStrings() {
  const file = path.join(root, 'scripts/provenance-producers.json')
  const feed = JSON.parse(readFileSync(file, 'utf8')).find((p) => p.kind === 'feed')
  return feed?.leakChecks?.forbidStrings ?? []
}

function metaFacets(entry) {
  const facets = entry.domains.slice(0, 3).map((d) => ({ text: d }))
  if (entry.tech.length) facets.push({ text: entry.tech.join(' · '), tech: true })
  const status = trimStatus(entry.status)
  if (status) facets.push({ text: status })
  if (entry.year && !hasYear(status)) facets.push({ text: String(entry.year) })
  return facets
    .map(
      (f) =>
        `<span class="ds-row__facet${f.tech ? ' ds-row__facet--tech' : ''}">${esc(f.text)}</span>`,
    )
    .join('\n            ')
}

// The row shows the lead segment of the feed title (before the " — " tagline) for a one-line
// entry; the full title rides along as a tooltip. A short feed displayName is a v1 nicety.
function row(entry, inPrimary = false) {
  const flagship = inPrimary && entry.flagship
  const name = entry.title.split(' — ')[0]
  const title = entry.href
    ? `<a href="${esc(entry.href)}" class="ds-row__title" title="${esc(entry.title)}">${esc(name)}</a>`
    : `<span class="ds-row__title ds-row__title--static" title="${esc(entry.title)}">${esc(name)}</span>`
  const tag = flagship ? '\n            <span class="ds-row__flagship-tag">Flagship</span>' : ''
  const live = entry.live
    ? `\n            <a href="${esc(entry.live.url)}" class="ds-row__live" target="_blank" rel="noopener">${esc(hostOf(entry.live.url))}</a>`
    : ''
  return `        <li class="ds-row${flagship ? ' ds-row--flagship' : ''}">
          <div class="ds-row__head">
            ${title}${tag}
            <span class="ds-row__thesis">${esc(entry.thesis)}</span>${live}
          </div>
          <div class="ds-row__meta">
            ${metaFacets(entry)}
          </div>
        </li>`
}

function primarySection(featured) {
  if (!featured.length) return ''
  const rows = featured.map((e) => row(e, true)).join('\n')
  return `      <section class="dswork dswork__primary" aria-labelledby="primary-h">
        <h2 id="primary-h">Primary projects</h2>
        <ul class="ds-list">
${rows}
        </ul>
      </section>`
}

function groupSection(group) {
  const rows = group.projects.map((e) => row(e)).join('\n')
  return `      <section class="dswork dswork__group" aria-labelledby="g-${group.key}">
        <h2 class="dswork__group-title" id="g-${group.key}">${esc(group.label)} <span class="dswork__count">${group.projects.length}</span></h2>
        <ul class="ds-list">
${rows}
        </ul>
      </section>`
}

// Feed recurringMethods are slug labels (e.g. "governance-driven-development"); humanize for display.
const humanize = (s) => s.replace(/-/g, ' ')

function overviewBand(portfolio) {
  const dCount = portfolio.domains.length
  const domains = dCount >= 20 ? `${Math.floor(dCount / 10) * 10}+ domains` : `${dCount} domains`
  const tail = []
  if (portfolio.firstActive) {
    tail.push(`built continuously since ${String(portfolio.firstActive).slice(0, 4)}`)
  }
  if (portfolio.deployedCount === 1) tail.push('one of them deployed and live')
  else if (portfolio.deployedCount > 1) {
    tail.push(`${portfolio.deployedCount} of them deployed and live`)
  }
  const clause = tail.length ? ` — ${tail.join(', ')}` : ''
  // Methods line lights up only when the feed provides portfolio.recurringMethods (v1).
  const methods = portfolio.recurringMethods.length
    ? `\n        <p class="portfolio-overview__methods"><span class="portfolio-overview__methods-label">Recurring methods</span>${esc(portfolio.recurringMethods.map(humanize).join(' · '))}</p>`
    : ''
  return `      <div class="portfolio-overview">
        <p class="portfolio-overview__lead">
          <span class="portfolio-overview__metric">${portfolio.projectCount} projects</span> across
          <span class="portfolio-overview__metric">${domains}</span> in
          <span class="portfolio-overview__metric">${portfolio.languages.length} languages</span>${clause}.
        </p>${methods}
      </div>`
}

const NAV = [
  ['/#evidence', 'Evidence', false],
  ['/projects/', 'Work', true],
  ['/experience/', 'Experience', false],
  ['/research/', 'Research', false],
  ['/cv.html', 'CV', false],
  ['/contact.html', 'Contact', false],
]

function page(model) {
  const nav = NAV.map(
    ([href, label, active]) =>
      `          <li><a href="${href}"${active ? ' class="active"' : ''}>${label}</a></li>`,
  ).join('\n')
  const groups = model.groups.map(groupSection).join('\n\n')
  return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Body of work | Jeffrey Johnson</title>
    <meta name="description" content="The full body of Dr. Jeffrey Johnson's projects — shipped systems, prototypes, released packages, research, and teaching — grouped by kind.">
    <link rel="canonical" href="https://jvjohnson.dev/projects/">
    <link rel="icon" href="/assets/icons/jvj_16.svg" type="image/svg+xml">
    <link rel="stylesheet" href="/assets/jeffrey.css">
    <script type="module" src="/assets/menu.js"></script>

    <!-- Open Graph / LinkedIn Preview Tags -->
    <meta property="og:title" content="Body of work — Jeffrey V. Johnson, Ph.D.">
    <meta property="og:description" content="The full body of Dr. Jeffrey Johnson's projects — shipped systems, prototypes, released packages, research, and teaching — grouped by kind.">
    <meta property="og:type" content="website">
    <meta property="og:url" content="https://jvjohnson.dev/projects/">
    <meta property="og:site_name" content="jvjohnson.dev">
    <meta property="og:image" content="https://jvjohnson.dev/og-default.png">
    <meta property="og:image:width" content="1200">
    <meta property="og:image:height" content="630">
    <meta property="og:image:alt" content="Jeffrey V. Johnson, Ph.D. — Independent researcher and systems builder">
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:title" content="Body of work — Jeffrey V. Johnson, Ph.D.">
    <meta name="twitter:description" content="The full body of Dr. Jeffrey Johnson's projects — shipped systems, prototypes, released packages, research, and teaching — grouped by kind.">
    <meta name="twitter:image" content="https://jvjohnson.dev/og-default.png">
    <meta name="twitter:image:alt" content="Jeffrey V. Johnson, Ph.D. — Independent researcher and systems builder">
</head>
<body>
    <a href="#main-content" class="skip-link">Skip to main content</a>
    <nav class="site-nav">
      <div class="container">
        <a href="/" class="nav-left">Jeffrey Johnson</a>
        <ul class="nav-links">
${nav}
        </ul>
      </div>
    </nav>

    <main id="main-content">
      <div class="container">
        <h1>Body of work</h1>
        <p class="section-intro">A body of agentic-development work, built deliberately — researched, spec-driven, and provenance-backed. Grouped by kind, newest first.</p>

${overviewBand(model.portfolio)}

${primarySection(model.featured)}

${groups}
      </div>
    </main>

    <footer class="site-footer">
      <div class="container">
        <p class="footer-cta">Open to research-engineering roles and research collaboration where mathematical depth meets agentic-systems engineering. The fastest way to reach me is email: <a href="mailto:jeffrey@jvjohnson.dev">jeffrey@jvjohnson.dev</a>.</p>
        <nav class="footer-links" aria-label="Footer">
          <a href="/">← Back to portfolio</a>
          <a href="/contact.html">Contact</a>
        </nav>
        <p>&copy; 2026 Jeffrey Johnson &middot; Homer, Alaska &middot; <a href="/colophon.html">Colophon</a></p>
      </div>
    </footer>
</body>
</html>
`
}

function main() {
  const model = buildViewModel()
  const html = page(model)
  for (const needle of leakStrings()) {
    if (needle && html.includes(needle)) {
      throw new Error(`feed leak gate: forbidden string "${needle}" present in generated ${OUT}`)
    }
  }
  writeFileSync(path.join(root, OUT), html)
  const summary = model.groups.map((g) => `${g.label} ${g.projects.length}`).join(' · ')
  console.log(`✓ feed → ${OUT} (${model.portfolio.projectCount} projects — ${summary})`)
}

main()
